Fixed motes being thrown at invisible places
lukakama/rimworld-mod-real-fow pull request #15
Opened 2020-06-01 12:44 UTC by OrionFive

Here's a fix for issue #9 as a little goody because I'm having one of these days.

2020-06-07 08:05 UTC, lukakama requested changes
Thanks for the contribution! Please just fix the indentation (use tabs instead of spaces) and I will merge it ASAP.

2020-06-07 10:52 UTC, OrionFive commented
I guess I can do that for you, as soon as I find the time.

2020-06-09 10:52 UTC, OrionFive commented
I hope it's good now. It's hard for me to see.

2020-06-13 13:52 UTC, lukakama approved these changes

2020-06-13 13:52 UTC, merged